### ISSUE TITLE
Manual setup

### ISSUE THREAD

**Issue by eliassal** [veler/DevToys#630] opened 2022-08-08 10:53 UTC
### Description

OK, great tool it seems. I downloaded the zip file but not sure how to run it. which or where is the executable file?
Thanks for your help

### Steps To Reproduce

Download zip file
Extract
search for an executable

### Expected behavior

Find an executable to run in the zipped file

### DevToys Version

DevToys-1.0.9.0

### Relevant Assets/Logs

Not able to run

I fired VS2022, opened the solution and tried to build, I got the following errors

```
Rebuild started...
Restored C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\shared\DevToys.Shared\DevToys.Shared.csproj (in 32 ms).
Restored C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.OutOfProcService\DevToys.OutOfProcService.csproj (in 33 ms).
Restored C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\DevToys.MonacoEditor.csproj (in 407 ms).
Restored C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys\DevToys.csproj (in 620 ms).
Restored C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\DevToys.Startup\DevToys.Startup.wapproj (in 633 ms).
Restored C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\tests\DevToys.Tests\DevToys.Tests.csproj (in 786 ms).
1>------ Rebuild All started: Project: DevToys.Shared, Configuration: Debug Any CPU ------
1>DevToys.Shared -> C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\AnyCPU\DevToys.Shared\netstandard2.0\DevToys.Shared.dll
2>------ Rebuild All started: Project: DevToys.OutOfProcService, Configuration: Debug x64 ------
3>------ Rebuild All started: Project: DevToys.MonacoEditor, Configuration: Debug x64 ------
2>Failed to resolve WinRT.Runtime.dll.
2>DevToys.OutOfProcService -> C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\x64\DevToys.OutOfProcService\net6.0-windows10.0.19041.0\DevToys.OutOfProcService.dll
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(1,21): error TS6053: Build:File 'C:/Projects/tools/DevToys-1.0.9.0/DevToys-1.0.9.0/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(12,12): error TS2304: Build:Cannot find name 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(23,35): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(55,43): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(80,31): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(95,35): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(110,36): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(116,40): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(117,45): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(124,5): error TS2304: Build:Cannot find name 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(141,5): error TS2304: Build:Cannot find name 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(147,5): error TS2304: Build:Cannot find name 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(164,5): error TS2304: Build:Cannot find name 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(1,21): error TS6053: Build:File 'C:/Projects/tools/DevToys-1.0.9.0/DevToys-1.0.9.0/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(5,12): error TS2304: Build:Cannot find name 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(1,21): error TS6053: Build:File 'C:/Projects/tools/DevToys-1.0.9.0/DevToys-1.0.9.0/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
3>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(17,25): error TS2304: Build:Cannot find name 'monaco'.
4>------ Rebuild All started: Project: DevToys, Configuration: Debug x64 ------
4>  fatal: not a git repository (or any of the parent directories): .git
4>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(224,3): warning MSB3073: The command "..." exited with code 128.
4>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(323,3): warning GI001: Directory C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys is not in a Git repository. Cannot determine Git repository root.
4>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(472,3): warning MSB3073: The command "..." exited with code 128.
4>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys\DevToys.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd'
4>CSC : error CS0006: Metadata file 'C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd' could not be found
4>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
5>------ Rebuild All started: Project: DevToys.Tests, Configuration: Debug x64 ------
6>------ Rebuild All started: Project: DevToys.Startup, Configuration: Debug x64 ------
5>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\tests\DevToys.Tests\DevToys.Tests.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\x64\DevToys\DevToys.exe'
6>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1806,5): warning NU1702: ProjectReference 'C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.OutOfProcService\DevToys.OutOfProcService.csproj' was resolved using '.NETCoreApp,Version=v7.0' instead of the project target framework '.NETFramework,Version=v4.5.1'. This project may not be fully compatible with your project.
6>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(841,5): warning : Package signing is enabled but no thumbprint or certificate path is specified.
6>fatal: not a git repository (or any of the parent directories): .git
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(224,3): warning MSB3073: The command "..." exited with code 128.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(323,3): warning GI001: Directory C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys is not in a Git repository. Cannot determine Git repository root.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(472,3): warning MSB3073: The command "..." exited with code 128.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(1,21): error TS6053: Build:File 'C:/Projects/tools/DevToys-1.0.9.0/DevToys-1.0.9.0/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(12,12): error TS2304: Build:Cannot find name 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(23,35): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(55,43): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(80,31): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(95,35): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(110,36): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(116,40): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(117,45): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(124,5): error TS2304: Build:Cannot find name 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(141,5): error TS2304: Build:Cannot find name 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(147,5): error TS2304: Build:Cannot find name 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(164,5): error TS2304: Build:Cannot find name 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(1,21): error TS6053: Build:File 'C:/Projects/tools/DevToys-1.0.9.0/DevToys-1.0.9.0/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(5,12): error TS2304: Build:Cannot find name 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(1,21): error TS6053: Build:File 'C:/Projects/tools/DevToys-1.0.9.0/DevToys-1.0.9.0/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(17,25): error TS2304: Build:Cannot find name 'monaco'.
6>Done building project "DevToys.MonacoEditor.csproj" -- FAILED.
6>Done building project "DevToys.csproj".
6>fatal: not a git repository (or any of the parent directories): .git
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(224,3): warning MSB3073: The command "..." exited with code 128.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(323,3): warning GI001: Directory C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys is not in a Git repository. Cannot determine Git repository root.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\packages\gitinfo\2.2.0\build\GitInfo.targets(472,3): warning MSB3073: The command "..." exited with code 128.
5>CSC : error CS0006: Metadata file 'C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\x64\DevToys\DevToys.exe' could not be found
5>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
6>C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\src\dev\impl\DevToys\DevToys.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd'
6>CSC : error CS0006: Metadata file 'C:\Projects\tools\DevToys-1.0.9.0\DevToys-1.0.9.0\bin\Debug\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd' could not be found
6>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
6>Done building project "DevToys.csproj" -- FAILED.
6>Done building project "DevToys.Startup.wapproj" -- FAILED.
========== Rebuild All: 2 succeeded, 4 failed, 0 skipped ==========
```

**Comment by jai-dewani** [comment] 2022-10-07 04:48
If you want to install it on your system the [Manual Installation](https://github.com/veler/DevToys#manual) step suggests to download the *.msixbundle file and double click on it

**Comment by Randle-Lanre** [comment] 2023-11-14 18:53
currently experiencing same problem, @eliassal  were you able to resolve this ?

**Comment by eliassal** [comment] 2023-11-17 17:49
No Randle-Lanre

**Comment by Randle-Lanre** [comment] 2023-11-22 19:55
@eliassal you are getting the error because you haven't run `init.ps1`

it is at the root directory of your DevToys folder, and it will restore and install neccessary components for you to be able to build and run DevToys on your machine. ref [contributing guide](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)

please try the suggestion and let me know if that fixes it for you.


![image](https://github.com/veler/DevToys/assets/19264390/aa92c860-607b-4dde-a0d8-521516c740e0)

**Comment by eliassal** [comment] 2023-11-23 10:34
Thanks @Randle-Lanre , I did run init.psopened the solution in VS2022, right away I get

![image](https://github.com/veler/DevToys/assets/8447864/79ab55cb-25a0-43a8-8420-e7eb0884603a)

I click Ok it fails

And several projects ar in unloaded state

![image](https://github.com/veler/DevToys/assets/8447864/6ad18d70-c4de-4fc9-a841-28d3290ac6a8)

**Comment by Randle-Lanre** [comment] 2023-11-23 10:47
@eliassal , 
could you try the following 
 Open VS installer ---> Click "more"  ---> click import configuration 
 
 then import `vsconfig2022` ( you can find this in the directory as `init.ps`)
 
 
 if you had done this step previous, can you share  your current workload ?  vs installer --> Modify   (attach a screenshot of the next screen) 
 
 
also could you share what version of windows you are running and the current build

**Comment by eliassal** [comment] 2023-11-23 11:49
@Randle-Lanre I got a message inside VS indicating SDK UAP is missing and I went and installed it. Now when I open the project version 1.0.13, they are all loaded but does not compile
![image](https://github.com/veler/DevToys/assets/8447864/e2598a1d-6f69-4f6a-9d32-417da71b1fc9)
Here is a snapshot of vs installer

![image](https://github.com/veler/DevToys/assets/8447864/8246aaa6-00c1-478d-b966-a335646d0859)

**Comment by eliassal** [comment] 2023-11-23 11:52
And here is what happens when I do import config2022

![image](https://github.com/veler/DevToys/assets/8447864/68837311-0080-4761-a09f-18f8e5556edb)

**Comment by Randle-Lanre** [comment] 2023-11-23 11:56
> And here is what happens when I do import config2022
> 
> ![image](https://user-images.githubusercontent.com/8447864/285197276-68837311-0080-4761-a09f-18f8e5556edb.png)

https://github.com/veler/DevToys/issues/976#issue-1990872317

**Comment by Randle-Lanre** [comment] 2023-11-23 11:58
@eliassal  could you include your version of windows and build

**Comment by eliassal** [comment] 2023-11-23 12:11
Here is windows details

![image](https://github.com/veler/DevToys/assets/8447864/10f45a25-3024-479d-b7e7-97dfb3ac6594)

**Comment by eliassal** [comment] 2023-11-23 14:34
After updating some target versions, now when I try to build DevToys I get
![image](https://github.com/veler/DevToys/assets/8447864/0ed9a2e2-9b07-4da9-8309-27e42162486a)

**Comment by eliassal** [comment] 2023-11-23 14:58
I went to Build Batch and checked only Debug64 for the 4 projects and build was successful. However, when I switch to powershell and type
`` .\DevToys.exe
nothing happens
I tried 
`.\DevToys.exe:?tool=jsonyaml`

I get
.\DevToys.exe:?tool=jsonyaml: The term '.\DevToys.exe:?tool=jsonyaml' is not recognized as a name of a cmdlet, function, script file, or executable program.
So how can I use the executable?
![image](https://github.com/veler/DevToys/assets/8447864/9bfc3570-83c6-4824-98d7-73b931ee5d12)

**Comment by eliassal** [comment] 2023-11-23 17:18
Some good news, inside VS2k22, right-clicked DevTops project > Sartinstance, and hop, It is working like a charm so I am not sure why it is nor running from powershell

![image](https://github.com/veler/DevToys/assets/8447864/beacb807-831d-4881-bc52-49c6f7bd4381)

**Comment by veler** [comment] 2023-11-23 17:55
Hello,

Catching up on this thread. :)

1. Oops, I need to update the `vs2022.vsconfig`, sorry.
2. DevToys 1.0 is a UWP app. By design, you can't double click the .exe and expect it to run. So it's normal it wasn't working. This will change in DevToys 2.0 (see `dev\2.0` branch) as it's not a UWP app anymore.

Closing this issue as your problem got solved :-)

**Closed by veler** 2023-11-23 17:55 UTC
Labels: bug

**Comment by eliassal** [comment] 2023-11-23 18:32
OK, but in the "How to run DevToys", under powershell, it is indicated that we can do

start devtoys:?tool=jsonyaml 

Am I mistaken?

**Comment by veler** [comment] 2023-11-24 22:40
Oh, that only works when the app is installed on the computer, which is what VS does when it build and runs the app.
