### ISSUE TITLE
JSON to C# POCO Generator

### ISSUE THREAD

**Issue by jakubkozera** [veler/DevToys#374] opened 2022-02-11 14:10 UTC
### What's the Problem?

It would be very helpful if the tool could generate a C# (or other language) class based on a pasted JSON object

### Solution/Idea

Add a generator which would parse and validate a JSON object and if its vaild, it would create a C# class according to the JSON properties/nested objects

### Alternatives

https://json2csharp.com/
https://quicktype.io/csharp

**Comment by vvafel** [comment] 2022-02-14 00:16
good idea

**Comment by rsunde** [comment] 2022-02-15 16:31
I concur,

I was thinking of adding myself, but I saw a BIG PR that refactors the converters.

will wait.

**Comment by btiteux** [comment] 2022-03-04 17:59
Hello,

It's seems that this issue is a duplicate of this one #6

**Closed by btiteux** 2022-03-04 17:59 UTC
