### ISSUE TITLE
Base64 image crash

### ISSUE THREAD

**Issue by chen-chunk** [veler/DevToys#880] opened 2023-07-14 03:24 UTC
### Current behavior

After opening the picture and minimizing the application, the program will crash when you operate it again.

### How to reproduce it (as minimally and precisely as possible)

1. Open the picture
2. Minimize the application
3. Wait 20 seconds
4. Close the picture

### Expected behavior

program crash

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

版本 1.0.12.0 | X64 | RELEASE | 94bb8213 | 94bb8213

### Relevant Assets/Logs

# - [07/14/2023 11:22:55]
Feature name: SmartDetection - Check if tool is recommended
Custom message: Tool : Xml Validator
Exception message: Data at the root level is invalid. Line 1, position 1.
Exception stack trace:
   at System.Xml.XmlTextReaderImpl.Throw(Exception) + 0x6c
   at System.Xml.XmlTextReaderImpl.Throw(String, String) + 0x56
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace() + 0x1a5
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent() + 0x22d
   at System.Xml.XmlTextReaderImpl.Read() + 0x355
   at System.Xml.XmlTextReader.Read() + 0xf
   at System.Xml.Schema.Parser.StartParsing(XmlReader, String) + 0xb7
   at System.Xml.Schema.Parser.Parse(XmlReader, String) + 0x10
   at System.Xml.Schema.XmlSchema.Read(XmlReader, ValidationEventHandler) + 0x86
   at DevToys.ViewModels.Tools.XmlValidator.XmlValidatorToolProvider.ValidateXsdData(String) + 0x122
   at DevToys.ViewModels.Tools.XmlValidator.XmlValidatorToolProvider.CanBeTreatedByTool(String) + 0x18
   at DevToys.Api.Tools.ToolProviderViewItem.<UpdateIsRecommendedAsync>d__40.MoveNext() + 0xc0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at DevToys.ViewModels.MainPageViewModel.<>c__DisplayClass88_1.<<UpdateRecommendedToolsAsync>b__2>d.MoveNext() + 0x107

**Comment by veler** [comment] 2023-08-06 01:02
This is likely due to an issue with the Suspended mode of UWP app life cycle. If confirmed, it should be fixed in DevToys 2.0, which won't be a UWP app and won't have this state,

**Closed** 2023-10-16 00:55 UTC
Labels: bug
