### ISSUE TITLE
Convert JSON data to its model definition (open api, json schema...)

### ISSUE THREAD

**Issue by FranciscoNadal1** [veler/DevToys#241] opened 2022-01-24 21:47 UTC
### What's the Problem?

I think it would be very cool if we could directly convert a json payload to its model definition: open api, json schema... 
In the future, maybe make it a tool that took the corresponding json and converted it to a C#/Java/php/python... class model

Also the opposite, given a model definition, generate a json with mock values.

### Solution/Idea

It could be done with a few tweeks to the Json<> Yaml already existing tool, for the types, you can check for string/num/data/bools

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by btiteux** [comment] 2022-03-04 17:59
Hello,

It's seems that this issue is a duplicate of this one #6

**Closed by btiteux** 2022-03-04 17:59 UTC
