### ISSUE TITLE
Not Responding and automatically closed

### ISSUE THREAD

**Issue by MGhandour92** [veler/DevToys#711] opened 2022-11-16 11:14 UTC
When I select (**Base64 Text Encoder / Decoder**) Option. The app stop responding and closes.

1. I have installed with manual option
2. Windows 10 build 19045.2251

![Screenshot_1](https://user-images.githubusercontent.com/12641187/202166084-a9d3ae6c-f6d0-4747-a94b-04bee51b0afe.png)

**Comment by MCrank** [comment] 2022-11-19 21:00
Probable duplicate of #675 and #692 and proposed fix in PR #690?

**Comment by veler** [comment] 2023-03-18 06:15
Duplicate with #757

**Closed by veler** 2023-03-18 06:15 UTC
