### ISSUE TITLE
Pin or favourite tools

### ISSUE THREAD

**Issue by savioret** [veler/DevToys#264] opened 2022-01-26 09:26 UTC
### What's the Problem?

As there are a lot of tools an (and more coming) it would be nice to be able to pin the most used ones and have a quick access to them.

### Solution/Idea

![image](https://user-images.githubusercontent.com/5497332/151136808-cd3cc31c-a53d-4784-95c8-8e9343892b4b.png)

This is basically the idea, any tool can be pinned (using a toggle button or similar) and will be shown in a new group below "All tools".

### Alternatives

Sorry I don't have any.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE | 3f367f1 | 3f367f1

**Comment by akarboush** [comment] 2022-01-26 12:19
Duplicate of #75

**Closed** 2022-01-26 17:02 UTC
Labels: duplicate
