### ISSUE TITLE
Tool search doesn't work correctly

### ISSUE THREAD

**Issue by NikolayEKolev** [veler/DevToys#608] opened 2022-07-22 22:31 UTC
### Description

Two scenarios:
1. When you type 'XML' in the search box and try to select it with the down arrow, the first entry is always selected - 'XML Formatter'.
2. When 'XML Validator' is typed in the search box and Enter is pressed both 'XML Validator' and 'XML Formatter' are displayed.

### Expected behavior

1. When you type 'XML' in the search box and try to select with the down arrow to be able to select a second, third tool from the drop down menu.
2. When 'XML Validator' is typed in the search box and Enter is pressed only 'XML Validator' is displayed.

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

### Relevant Assets/Logs

https://user-images.githubusercontent.com/70388317/180576737-4e794be6-dddd-43ff-90c8-1f78ff721196.mp4

https://user-images.githubusercontent.com/70388317/180576739-0d27352d-35f5-4c07-87f1-c94e234318f9.mp4

**Comment by araujofrancisco** [comment] 2022-07-27 21:32
It seems like the issue happens due the search is been done by MenuDisplayName instead of SearchDisplayName and while many tools have both values set the same in the strings XML Formatter differs. I am doing a review to see if it the issue is in the string itself or we need to apply a code fix.

![imagen_2022-07-27_173003714](https://user-images.githubusercontent.com/3943185/181375917-234fcc98-2549-47a3-93ed-5285051104ab.png)

![imagen_2022-07-27_173019588](https://user-images.githubusercontent.com/3943185/181375953-9581bdf5-1f56-44b2-81a8-fd0005bf9fc1.png)

![imagen_2022-07-27_173028176](https://user-images.githubusercontent.com/3943185/181375980-45660351-c5d1-4486-8500-3f0d2bd93f5f.png)

**Comment by NikolayEKolev** [comment] 2022-10-11 07:54
ОК. thanks.

На чт, 28.07.2022 г. в 0:32 ч. Francisco Araujo ***@***.***>
написа:

**Comment by veler** [comment] 2023-05-04 15:02
Issue still happens in DevToys 1.* but is fixed in 2.0: 

https://github.com/veler/DevToys/commit/5ee1a666af3aff22491885ffcf6aa4fdfca5e2be

https://github.com/veler/DevToys/commit/60a32e11088e2f89d2988c1c7aaa403608cb1c5b#diff-4620c52ac3ff9920b8ec8ca1791b48d2b476bf7ddbdba67b2d76bc536e5bc092

https://github.com/veler/DevToys/commit/38cdbf88246befd3f8d6f0138e2a75ff9427bbb5

https://github.com/veler/DevToys/commit/a9e5b2d430145c457124c9452a7192cd9809530a

**Closed by veler** 2023-05-04 15:02 UTC
Labels: bug, enhancement

**Comment by pureiboi** [comment] 2023-05-05 15:35
> Issue still happens in DevToys 1.* but is fixed in 2.0:
> 
> [5ee1a66](https://github.com/veler/DevToys/commit/5ee1a666af3aff22491885ffcf6aa4fdfca5e2be)
> 
> [60a32e1#diff-4620c52ac3ff9920b8ec8ca1791b48d2b476bf7ddbdba67b2d76bc536e5bc092](https://github.com/veler/DevToys/commit/60a32e11088e2f89d2988c1c7aaa403608cb1c5b#diff-4620c52ac3ff9920b8ec8ca1791b48d2b476bf7ddbdba67b2d76bc536e5bc092)
> 
> [38cdbf8](https://github.com/veler/DevToys/commit/38cdbf88246befd3f8d6f0138e2a75ff9427bbb5)
> 
> [a9e5b2d](https://github.com/veler/DevToys/commit/a9e5b2d430145c457124c9452a7192cd9809530a)

oh yes. i got the steps wrong. my bad.
