### ISSUE TITLE
Crash when dragging files from vsc

### ISSUE THREAD

**Issue by RadNotRed** [veler/DevToys#686] opened 2022-10-08 02:21 UTC
### Description

Crashes when dragging files from Visual Studio Code into checksum generator

### Steps To Reproduce

Open vsc
Try to drag a file into checksum generator
Crashes

### Expected behavior

Get the actual checksum of the file dragged

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/9738206/logs.txt)

**Comment by alchemistis** [comment] 2022-10-18 02:07
I reproduced the issue and got the following exception:

```
# - [10/17/2022 22:00:08]
Feature name: Unhandled problem
Custom message: 
Exception message: Invalid FORMATETC structure (Exception from HRESULT: 0x80040064)
Exception stack trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at DevToys.UI.Controls.FileSelector.<Grid_DragOver>d__35.MoveNext() + 0x109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   ```

After doing some quick research, it looks like it's a known issue with VS Code not playing well with the DnD functionality.

Source:
[Cannot drag/drop file from VS Code to other apps due to invalid data object #91132](https://github.com/microsoft/vscode/issues/91132)
[Better drag and drop / clipboard integration of files across applications #164](https://github.com/microsoft/vscode/issues/91132)

I don't know if it's something that could be worked around (as in getting it to work properly, even with the mentioned issues) or if it should just gracefully fail instead. I also tried dragging files from VS Code to other applications and they just seem to either prevent or ignore it.

**Comment by veler** [comment] 2023-10-16 01:35
Hi,
I noticed the issue doesn't reproduce anymore using VS Code. Closing this issue for now.

**Closed by veler** 2023-10-16 01:35 UTC
Labels: bug
