### ISSUE TITLE
UUID fast generation

### ISSUE THREAD

**Issue by btbenjamin** [veler/DevToys#505] opened 2022-04-27 06:46 UTC
### What's the Problem?

When i want to get a new UUID one by one and copy them whatever i want i should  :

1. Click on the generate btn
2. Select + CTRL+V or click copy btn
3. Clear the console
4. And restart step 1

Another thing, the buttons are not next to each other so the steps are not that fast

### Solution/Idea

Create a btn "Generate and copy clipboard" 

Or 

Create shortcut for generate/copy/clear

### Alternatives

Create a btn "Generate and copy clipboard" 

Or 

Create shortcut for generate/copy/clear

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.6.0 | X64 | RELEASE | c032ebb | c032ebb

**Comment by kressnick25** [comment] 2023-06-04 10:32
Duplicate of #383?

**Comment by veler** [comment] 2023-06-04 22:11
Good catch! Thanks! Closing

**Closed by veler** 2023-06-04 22:11 UTC
Labels: enhancement
