### ISSUE TITLE
rearrange options

### ISSUE THREAD

**Issue by darwin1989-bit** [veler/DevToys#787] opened 2023-04-05 04:28 UTC
### What feature or new tool do you think should be added to DevToys?

A good improvement for this super tool would be to relocate the options that you have in the tool, since the options take up a lot of space and you can't see much of the content, I attached a screenshot.

![image](https://user-images.githubusercontent.com/74321331/229980716-21a86212-160f-4e34-8c75-c9d87ccf5221.png)

Additional I would like to be able to change the size of the font or place another type of font.

Greetings and thanks for your great work.

### Why do you think this is needed?

This would help a lot to see the content more clearly and have a better visualization.

**Comment by veler** [comment] 2023-04-06 04:08
Hi,
Thanks for this suggestion. We are currently working on DevToys 2.0 and tried to address a similar issue by introducing a compact mode. It will have an effect that looks like this (currently a prototype).

![compactmode](https://user-images.githubusercontent.com/3747805/224606675-1685d38c-14c6-4d2f-bdca-d50ce9777434.gif)

Do you think it would be enough to address the issue you mentioned?

**Comment by veler** [comment] 2023-05-31 02:53
Potential duplicate of #678

**Closed by veler** 2023-05-31 02:53 UTC
Labels: enhancement, need more info

**Comment by darwin1989-bit** [comment] 2023-05-31 04:01
thanks for the new features
