### ISSUE TITLE
Be able to convert from/to timestamp

### ISSUE THREAD

**Issue by savioret** [veler/DevToys#263] opened 2022-01-26 09:14 UTC
### What's the Problem?

Dealing with UNIX timestamps and converting back and forth to human readable dates would be great to be implemented.

### Solution/Idea

Must:
Convert from Unix epoch time to a human readable
Convert from human readable (year month day hour minute second) to a epoch timestamp.

Could:
Define a parseable format from the human readable input for example:
"Y-m-d H:i:s"
For converting from human readable format there could be 2 options:
a) The parseable string that should match the defined date format.
b) Filling some placeholders (text boxes) for year, month, day, hour, minute and second.

Example of converting from timestamp to human readable date:
```
Input: 1643045248
Date format: Y-m-d H:i:s
Output: 2022-01-24 18:27:28
```

### Alternatives

Not sure about this

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE | 3f367f1 | 3f367f1

**Comment by akarboush** [comment] 2022-01-26 12:16
Duplicate of #106

**Closed** 2022-01-26 17:02 UTC
Labels: duplicate
